version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8

services:
  redis:
    image: "redis:6.0.5-alpine"
    ports:
      - "6379:6379"
  file_worker:
    build:
      context: .
      args:
        <<: *build_args
    image: send_mail.worker
    volumes:
      - ./:/app
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/
      OUTPUT_DIR: /app/output
  # smtp_worker:
  #   build:
  #     context: .
  #     args:
  #       <<: *build_args
  #   image: send_mail.worker
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - redis
  #   environment:
  #     REDIS_URL: redis://redis:6379/
  #     SMTP_HOST: smtp.example.com

